# Generated by Django 5.0.7 on 2024-07-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_foodpost_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpost',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='foodpost',
            name='meal',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20),
        ),
    ]
